# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Arblj0DJ7P7HjkC3IW3gIFGK-KSkJ8iH
"""

import numpy as np
import tensorflow as tf

import time

tf.test.gpu_device_name()#check GPU

shape = 5000

"""Using Numpy Array"""

np_array = np.random.uniform(size=[shape, shape])

start = time.time()
for i in range(10):
  np.matmul(np_array, np_array)
end = time.time()

time_period = end - start

print(f'{time_period}, seconds')

"""Using tensorflow array"""

tf_array = tf.random.uniform([shape, shape])

start = time.time()
for i in range(10):
  tf.matmul(tf_array, tf_array)
end = time.time()

time_period = end - start

print(f'{time_period}, seconds')